## name: Cyberpunk (V1xEr3bus)
# ╔════════════════════╗
# ║     Basic Colors   ║
# ╚════════════════════╝
foreground #FF003C
background #000000
selection_foreground none
selection_background #000000

# ╔══════════════════════╗
# ║    Cursor & URL      ║
# ╚══════════════════════╝
cursor #00F0FF
cursor_text_color background
url_color #FCEE09

# ╔═════════════════════════════╗
# ║   Window & Bell Borders     ║
# ╚═════════════════════════════╝
active_border_color #FF003C
inactive_border_color #0e0e0e
bell_border_color #FF003C
visual_bell_color none

# ╔═════════════════════╗
# ║       Tab Bar       ║
# ╚═════════════════════╝
active_tab_foreground #060606
active_tab_background #FF003C
inactive_tab_foreground #FF003C
inactive_tab_background #060606
tab_bar_background #060606
tab_bar_margin_color #060606

# ╔═════════════════════╗
# ║      ANSI Colors    ║
# ╚═════════════════════╝
# black / brblack
color0  #060606
color8  #1a1a1a

# red / brred  (Main)
color1  #FF003C
color9  #FF335F

# green / brgreen
color2  #00FF9C
color10 #36FFB9

# yellow / bryellow  (Accent)
color3  #FCEE09
color11 #FDE93F

# blue / brblue
color4  #0A84FF
color12 #4AA3FF

# magenta / brmagenta
color5  #D57BFF
color13 #C592FF

# cyan / brcyan (Secondary)
color6  #00F0FF
color14 #5AF7FF

# white / brwhite
color7  #EEFFFF
color15 #FFFFFF
